# Production Configuration for ASN Proxy Server

server:
  port: 3000
  host: "0.0.0.0"
  
apache:
  upstream: "http://localhost:8080"
  
asn:
  # Production ASN sources with faster refresh
  sources:
    - url: "https://raw.githubusercontent.com/O-X-L/risk-db/main/asn.json"
      format: "json"
      refresh_interval: 1800  # 30 minutes
    - url: "https://raw.githubusercontent.com/NullifiedCode/ASN-Lists/main/malicious_asns.txt"
      format: "txt"
      refresh_interval: 1800
  
  custom_list: "./config/custom_asn.json"
  cache_ttl: 600  # 10 minutes
  
captcha:
  difficulty: "medium"
  expiry: 300  # 5 minutes
  verification_ttl: 7200  # 2 hours for production
  
ip_resolution:
  maxmind_db: "./data/GeoLite2-ASN.mmdb"
  fallback_api: "https://ipapi.co/{ip}/json/"
  cache_ttl: 1800  # 30 minutes
  
logging:
  level: "info"
  max_files: 30
  max_size: "50m"
